### ISSUE TITLE
Weekly Scrum - Mar. 5

### ISSUE THREAD

**Issue by aeiou80** [aeiou80/Mini-SurveyMonkey-4806#1]

**Comment by aeiou80** [comment]
**What have I done this week?**
- Created the repo
- Integrated with CircleCI
- Created Heroku app https://mini-surveymonkey-4806.herokuapp.com/
- Created DB Schema

**What will I do next week?**
- Integration testing
- Helping out where needed

**What is holding me back?**
- Nothing at this time

**Comment by frankliu197** [comment]
What have I done this week?

- Created a template project structure in spring
- created questions model (and its subclasses), its controller, repository, and tests.

What will I do next week?
Adding pages in the frontend, such as the histogram.

What is holding me back?
Nothing at this time

**Comment by doodlehead** [comment]
## What have I done this week?
- Create front-end React app repo
- Create basic application shell (header, sidenav, material-ui component library, basic application structure)
- Create "survey list" page
  - get all surveys
  - create survey
  - delete survey
- Create "edit survey" page
  - view all questions belonging to a survey
  - add a question to a survey
    - multiple choice
    - range
    - text question
  - delete a question from a survey

## What will I do next week?
- design and planning for frontend and backend
- pages/components relating to answering a survey

## What is holding me back?
- Design for backend and front end are not super fleshed out

**Comment by Binyamin-Brion** [comment]
What have I done this week?
Create model, controller and repository, along with test, for answer and survey

What will I do next week?
Further design for front-end and back-end, and helping out where needed

What is holding me back?
Nothing
