### ISSUE TITLE
Weekly Scrum - Mar. 18

### ISSUE THREAD

**Issue by aeiou80** [aeiou80/Mini-SurveyMonkey-4806#11]

**Comment by aeiou80** [comment]
**What have I done this week?**
- Close surveys and disabled editing survey after closure
- Answer results page

**What will I be doing next week?**
- ???

**What is blocking me?**
- Nothing at this time

**Comment by doodlehead** [comment]
## What have I done this week?
- Implement `User` model, `UserController` and `UsersRepository`
- Implement User authentication with logging in and logging out
- Use JsonViews
- Allow H2 database console to be accessed remotely

## What will I be doing next week?
- ???

## What is blocking me?
- Nothing

**Comment by frankliu197** [comment]
## What have I done this week?
- Implement login, logout, register on frontend

## What will I be doing next week?
- ???

## What is blocking me?
- CORS

**Comment by Binyamin-Brion** [comment]
### What have I done this week?

* Implement ability to answer questions in survey (including for non-authenticated users)

### What will I be doing next week?

* ? x 3

### What is blocking me?

* Nothing
