### ISSUE TITLE
Weekly Scrum - April 4th

### ISSUE THREAD

**Issue by aeiou80** [aeiou80/Mini-SurveyMonkey-4806#24]

**Comment by aeiou80** [comment]
**What have I done this week?**
- Finished Home page and styled other pages
- Client-side question creation validation
- UML & Schema Diagrams

**What will I do next week?**
- N/A

**What is holding me back?**
- Nothing at this time

**Comment by frankliu197** [comment]
**What have I done this week?**
- Integration Testing
- Fix deletion of surveys when it has been answered

**What will I do next week?**
- N/A

**What is holding me back?**
- Nothing at this time

**Comment by doodlehead** [comment]
## What have I done this week?
- Styling fixes
- Front-end validation for min/max values for range question creation
- Limit user to one response to each survey

## What will I do next week?
- Project is complete

## What is holding me back?
- Nothing

**Comment by Binyamin-Brion** [comment]
### What have I done this week

* Added thank you page after answering survey, that redirects user to home page of entire application

### What will I do next week

* Nothing

### What is holding me back

* Nothing
